# extensions:
#   basicauth/otlp:
#     client_auth:
#       username: "admin"
#       password: "admin"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
      processors: [batch]