import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { GoogleOAuthProvider } from '@react-oauth/google'
import Script from 'next/script'
import { fetchUserBySessionToken } from '@/api-calls/fetch-user-by-session-token'
import { GoogleAnalytics, sendGAEvent } from '@next/third-parties/google'
import { send } from 'node:process'
import { Analytics } from '@/components/Analytics'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const data = await fetchUserBySessionToken()

    return (
        <html lang="pt-BR">
            {/* {process.env.NODE_ENV !== 'development' && process.env.GA_ID && (
                <Analytics
                    GA_ID={process.env.GA_ID}
                    userEmail={data?.userId || null}
                />
            )} */}

            <Script
                src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GA_ID}`}
                strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    ${data?.userId ? `gtag('set', 'user_id', '${data.userId}');` : ''}

                    gtag('config', '${process.env.GA_ID}');
                `}
            </Script>

            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
                    {children}
                </GoogleOAuthProvider>
            </body>
        </html>
    )
}
