FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice \
    fonts-dejavu \
    fonts-liberation \
    fontconfig \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY fonts/ /usr/share/fonts/truetype/custom/

# Update the font cache of the system to recognize the new files
RUN fc-cache -f -v

EXPOSE 8080

CMD ["functions-framework", "--target=main", "--signature-type=http", "--port=8080"]